---
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Set Storage address fact for host
  set_fact:
    storage_bridge: "{{ 'ansible_' + swift.storage_network|replace('-', '_') }}"
  when:
    - swift is defined
    - swift.storage_network is defined
    - inventory_hostname in groups['swift_hosts']

- name: Set Storage_address fact for host
  set_fact:
    storage_address: "{{ hostvars[inventory_hostname][storage_bridge]['ipv4']['address'] | default(container_address) }}"
  when:
    - inventory_hostname in groups['swift_hosts']


# Setup Swift data accessibility
- name: Create swift user
  # Can we source normal openstack user/pass/endpoint data for this?
  # Does it have to be a lower privilege user?
  # create swift user {{ swift_access_user }}

- name: Create swift container
  # swift --os-auth-url={{ OS_AUTH_URL }} \
  #   --auth-version {{ OS_AUTH_VERSION }}\
  #   --os-project-name {{ OS_PROJECT_NAME }} \
  #   --os-project-domain-name {{ OS_PROJECT_DOMAIN_NAME }} \
  #    --os-username {{ OS_USERNAME }} --os-password {{ OS_PASSWORD }} \
  #    --os-user-domain-name {{ OS_USER_DOMAIN_NAME }} \
  #    post {{ swift_access_container }}

- name: Create check file
  # swift --os-auth-url={{ OS_AUTH_URL }} \
  #   --auth-version {{ OS_AUTH_VERSION }}\
  #   --os-project-name {{ OS_PROJECT_NAME }} \
  #   --os-project-domain-name {{ OS_PROJECT_DOMAIN_NAME }} \
  #    --os-username {{ OS_USERNAME }} --os-password {{ OS_PASSWORD }} \
  #    --os-user-domain-name {{ OS_USER_DOMAIN_NAME }} \
  #    upload {{ swift_access_container }} {{ swift_access_index }}

- name: Configure check container
  # swift --os-auth-url={{ OS_AUTH_URL }} \
  #   --auth-version {{ OS_AUTH_VERSION }}\
  #   --os-project-name {{ OS_PROJECT_NAME }} \
  #   --os-project-domain-name {{ OS_PROJECT_DOMAIN_NAME }} \
  #    --os-username {{ OS_USERNAME }} --os-password {{ OS_PASSWORD }} \
  #    --os-user-domain-name {{ OS_USER_DOMAIN_NAME }} \
  #    post -r '.r:*' {{ swift_access_container }}
  # swift --os-auth-url={{ OS_AUTH_URL }} \
  #   --auth-version {{ OS_AUTH_VERSION }}\
  #   --os-project-name {{ OS_PROJECT_NAME }} \
  #   --os-project-domain-name {{ OS_PROJECT_DOMAIN_NAME }} \
  #    --os-username {{ OS_USERNAME }} --os-password {{ OS_PASSWORD }} \
  #    --os-user-domain-name {{ OS_USER_DOMAIN_NAME }} \
  #    post -m 'web-index:index.html' {{ swift_access_container }}

- name: Retrieve check file URL
  # Generate a tempurl with a massively long 'expires' value
  # swift tempurl GET --absolute 4294967295 /v1/{{ swift_auth_account }}/{{ swift_access_container }}/index.html \
  #   {{ swift_temp_url_key }}
  # Should return something similar to:
  #   /v1/AUTH_c1fd7d36578049c9856d5f8f21e4be2c/web/index.html?temp_url_sig=31b92688ecfbf77eb73a9f05fa557c04790785c7&temp_url_expires=4294967295
  # Access similar to:
  # {{ maas_swift_proxy_scheme | default(maas_scheme)}}://{{ ip_address }}:8080/{{tempurl}}

# Setup Swift Server healthchecks
- include: ensure_local_checks.yml
  vars:
    checks: "{{ swift_checks_list }}"
